# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/dlg_task.ui'
#
# Created: Sun Jan 04 13:52:10 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(670, 380)
        Form.setMaximumSize(QtCore.QSize(670, 380))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/mainicon/res/wp.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.btn_cancel = QtGui.QPushButton(Form)
        self.btn_cancel.setGeometry(QtCore.QRect(360, 322, 85, 32))
        self.btn_cancel.setObjectName(_fromUtf8("btn_cancel"))
        self.btn_ok = QtGui.QPushButton(Form)
        self.btn_ok.setGeometry(QtCore.QRect(260, 322, 85, 32))
        self.btn_ok.setObjectName(_fromUtf8("btn_ok"))
        self.gridLayoutWidget = QtGui.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 651, 311))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(0, 0))
        self.label_6.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 2, 3, 1, 1)
        self.lbl_creator = QtGui.QLabel(self.gridLayoutWidget)
        self.lbl_creator.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lbl_creator.setObjectName(_fromUtf8("lbl_creator"))
        self.gridLayout_2.addWidget(self.lbl_creator, 2, 4, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_9.setMinimumSize(QtCore.QSize(0, 0))
        self.label_9.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 1, 5, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(60, 0))
        self.label_7.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 1, 3, 1, 1)
        self.cmb_TaskState = QtGui.QComboBox(self.gridLayoutWidget)
        self.cmb_TaskState.setMinimumSize(QtCore.QSize(115, 25))
        self.cmb_TaskState.setMaximumSize(QtCore.QSize(115, 16777215))
        self.cmb_TaskState.setObjectName(_fromUtf8("cmb_TaskState"))
        self.cmb_TaskState.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmb_TaskState, 1, 6, 1, 1)
        self.cmb_TaskPriority = QtGui.QComboBox(self.gridLayoutWidget)
        self.cmb_TaskPriority.setMinimumSize(QtCore.QSize(0, 25))
        self.cmb_TaskPriority.setMaximumSize(QtCore.QSize(110, 16777215))
        self.cmb_TaskPriority.setObjectName(_fromUtf8("cmb_TaskPriority"))
        self.cmb_TaskPriority.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmb_TaskPriority, 1, 4, 1, 1)
        self.cmb_TaskType = QtGui.QComboBox(self.gridLayoutWidget)
        self.cmb_TaskType.setMinimumSize(QtCore.QSize(0, 25))
        self.cmb_TaskType.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cmb_TaskType.setObjectName(_fromUtf8("cmb_TaskType"))
        self.cmb_TaskType.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmb_TaskType, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setMaximumSize(QtCore.QSize(60, 85))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.txt_desc = QtGui.QTextEdit(self.gridLayoutWidget)
        self.txt_desc.setMaximumSize(QtCore.QSize(16777215, 90))
        self.txt_desc.setObjectName(_fromUtf8("txt_desc"))
        self.gridLayout_2.addWidget(self.txt_desc, 4, 1, 1, 6)
        self.lbl_createtime = QtGui.QLabel(self.gridLayoutWidget)
        self.lbl_createtime.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_createtime.setMaximumSize(QtCore.QSize(140, 16777215))
        self.lbl_createtime.setObjectName(_fromUtf8("lbl_createtime"))
        self.gridLayout_2.addWidget(self.lbl_createtime, 2, 6, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_8.setMinimumSize(QtCore.QSize(0, 0))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 2, 5, 1, 1)
        self.lbl_exectime_title = QtGui.QLabel(self.gridLayoutWidget)
        self.lbl_exectime_title.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_exectime_title.setObjectName(_fromUtf8("lbl_exectime_title"))
        self.gridLayout_2.addWidget(self.lbl_exectime_title, 3, 3, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_12.setMinimumSize(QtCore.QSize(0, 0))
        self.label_12.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setMargin(0)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.dt_endtime = QtGui.QDateTimeEdit(self.gridLayoutWidget)
        self.dt_endtime.setMinimumSize(QtCore.QSize(0, 25))
        self.dt_endtime.setMaximumSize(QtCore.QSize(150, 16777215))
        self.dt_endtime.setObjectName(_fromUtf8("dt_endtime"))
        self.gridLayout_2.addWidget(self.dt_endtime, 3, 1, 1, 1)
        self.txt_executor = QtGui.QLineEdit(self.gridLayoutWidget)
        self.txt_executor.setEnabled(True)
        self.txt_executor.setMinimumSize(QtCore.QSize(0, 25))
        self.txt_executor.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txt_executor.setReadOnly(True)
        self.txt_executor.setObjectName(_fromUtf8("txt_executor"))
        self.gridLayout_2.addWidget(self.txt_executor, 2, 1, 1, 1)
        self.btn_auto = QtGui.QPushButton(self.gridLayoutWidget)
        self.btn_auto.setMaximumSize(QtCore.QSize(28, 25))
        self.btn_auto.setObjectName(_fromUtf8("btn_auto"))
        self.gridLayout_2.addWidget(self.btn_auto, 1, 2, 1, 1)
        self.btn_requester = QtGui.QPushButton(self.gridLayoutWidget)
        self.btn_requester.setMaximumSize(QtCore.QSize(28, 25))
        self.btn_requester.setObjectName(_fromUtf8("btn_requester"))
        self.gridLayout_2.addWidget(self.btn_requester, 2, 2, 1, 1)
        self.txt_TaskName = QtGui.QLineEdit(self.gridLayoutWidget)
        self.txt_TaskName.setMinimumSize(QtCore.QSize(0, 25))
        self.txt_TaskName.setObjectName(_fromUtf8("txt_TaskName"))
        self.gridLayout_2.addWidget(self.txt_TaskName, 0, 1, 1, 6)
        self.lbl_exectime = QtGui.QLabel(self.gridLayoutWidget)
        self.lbl_exectime.setObjectName(_fromUtf8("lbl_exectime"))
        self.gridLayout_2.addWidget(self.lbl_exectime, 3, 4, 1, 3)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.btn_cancel, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "任务", None))
        self.btn_cancel.setText(_translate("Form", "取消", None))
        self.btn_ok.setText(_translate("Form", "确定", None))
        self.label_6.setText(_translate("Form", "任务类型", None))
        self.label_2.setText(_translate("Form", "任务名称", None))
        self.label_3.setText(_translate("Form", "创建人", None))
        self.lbl_creator.setText(_translate("Form", "admin", None))
        self.label_9.setText(_translate("Form", "状态", None))
        self.label_7.setText(_translate("Form", "优先级", None))
        self.cmb_TaskState.setItemText(0, _translate("Form", "请选择状态", None))
        self.cmb_TaskPriority.setItemText(0, _translate("Form", "请选择优先级", None))
        self.cmb_TaskType.setItemText(0, _translate("Form", "请选择任务类型", None))
        self.label_5.setText(_translate("Form", "任务描述", None))
        self.lbl_createtime.setText(_translate("Form", "2015-01-01", None))
        self.label_8.setText(_translate("Form", "创建时间", None))
        self.lbl_exectime_title.setText(_translate("Form", "执行时间", None))
        self.label_12.setText(_translate("Form", "结束时间", None))
        self.label_4.setText(_translate("Form", "执行人", None))
        self.btn_auto.setText(_translate("Form", "...", None))
        self.btn_requester.setText(_translate("Form", "...", None))
        self.lbl_exectime.setText(_translate("Form", "未执行", None))

import res_rc
