# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/task.ui'
#
# Created: Tue Dec 30 23:33:19 2014
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(706, 343)
        Form.setMaximumSize(QtCore.QSize(1000, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/mainicon/res/wp.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.pushButton_2 = QtGui.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(340, 280, 80, 28))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton = QtGui.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(250, 280, 80, 28))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.layoutWidget = QtGui.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 662, 231))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setSpacing(15)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.txt_TaskName = QtGui.QLineEdit(self.layoutWidget)
        self.txt_TaskName.setMinimumSize(QtCore.QSize(0, 25))
        self.txt_TaskName.setObjectName(_fromUtf8("txt_TaskName"))
        self.gridLayout.addWidget(self.txt_TaskName, 0, 1, 1, 3)
        self.cmb_TaskType = QtGui.QComboBox(self.layoutWidget)
        self.cmb_TaskType.setMinimumSize(QtCore.QSize(130, 25))
        self.cmb_TaskType.setMaximumSize(QtCore.QSize(130, 16777215))
        self.cmb_TaskType.setObjectName(_fromUtf8("cmb_TaskType"))
        self.cmb_TaskType.addItem(_fromUtf8(""))
        self.cmb_TaskType.addItem(_fromUtf8(""))
        self.cmb_TaskType.addItem(_fromUtf8(""))
        self.cmb_TaskType.addItem(_fromUtf8(""))
        self.cmb_TaskType.addItem(_fromUtf8(""))
        self.cmb_TaskType.addItem(_fromUtf8(""))
        self.cmb_TaskType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmb_TaskType, 0, 5, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setMinimumSize(QtCore.QSize(0, 0))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 3, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(65, 0))
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 4, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(65, 0))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setMinimumSize(QtCore.QSize(65, 0))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 1, 2, 1, 1)
        self.txt_Creator = QtGui.QLineEdit(self.layoutWidget)
        self.txt_Creator.setMinimumSize(QtCore.QSize(0, 25))
        self.txt_Creator.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txt_Creator.setObjectName(_fromUtf8("txt_Creator"))
        self.gridLayout.addWidget(self.txt_Creator, 3, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 3, 3, 1, 1)
        self.cmb_TaskPriority = QtGui.QComboBox(self.layoutWidget)
        self.cmb_TaskPriority.setMinimumSize(QtCore.QSize(130, 25))
        self.cmb_TaskPriority.setMaximumSize(QtCore.QSize(130, 16777215))
        self.cmb_TaskPriority.setObjectName(_fromUtf8("cmb_TaskPriority"))
        self.cmb_TaskPriority.addItem(_fromUtf8(""))
        self.cmb_TaskPriority.addItem(_fromUtf8(""))
        self.cmb_TaskPriority.addItem(_fromUtf8(""))
        self.cmb_TaskPriority.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmb_TaskPriority, 1, 1, 1, 1)
        self.dt_endtime = QtGui.QDateTimeEdit(self.layoutWidget)
        self.dt_endtime.setMinimumSize(QtCore.QSize(130, 25))
        self.dt_endtime.setMaximumSize(QtCore.QSize(130, 16777215))
        self.dt_endtime.setObjectName(_fromUtf8("dt_endtime"))
        self.gridLayout.addWidget(self.dt_endtime, 1, 5, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        self.label_12.setMinimumSize(QtCore.QSize(0, 0))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 1, 4, 1, 1)
        self.cmb_TaskState = QtGui.QComboBox(self.layoutWidget)
        self.cmb_TaskState.setMinimumSize(QtCore.QSize(130, 25))
        self.cmb_TaskState.setMaximumSize(QtCore.QSize(130, 16777215))
        self.cmb_TaskState.setObjectName(_fromUtf8("cmb_TaskState"))
        self.cmb_TaskState.addItem(_fromUtf8(""))
        self.cmb_TaskState.addItem(_fromUtf8(""))
        self.cmb_TaskState.addItem(_fromUtf8(""))
        self.cmb_TaskState.addItem(_fromUtf8(""))
        self.cmb_TaskState.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmb_TaskState, 1, 3, 1, 1)
        self.lbl_createtime = QtGui.QLabel(self.layoutWidget)
        self.lbl_createtime.setObjectName(_fromUtf8("lbl_createtime"))
        self.gridLayout.addWidget(self.lbl_createtime, 3, 5, 1, 1)
        self.textEdit = QtGui.QTextEdit(self.layoutWidget)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 85))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout.addWidget(self.textEdit, 7, 1, 1, 5)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "任务", None))
        self.pushButton_2.setText(_translate("Form", "取消", None))
        self.pushButton.setText(_translate("Form", "确定", None))
        self.cmb_TaskType.setItemText(0, _translate("Form", "请选择任务类型", None))
        self.cmb_TaskType.setItemText(1, _translate("Form", "自动化", None))
        self.cmb_TaskType.setItemText(2, _translate("Form", "车机测试", None))
        self.cmb_TaskType.setItemText(3, _translate("Form", "App", None))
        self.cmb_TaskType.setItemText(4, _translate("Form", "Web平台", None))
        self.cmb_TaskType.setItemText(5, _translate("Form", "接口", None))
        self.cmb_TaskType.setItemText(6, _translate("Form", "性能测试", None))
        self.label_8.setText(_translate("Form", "创建时间", None))
        self.label_3.setText(_translate("Form", "创建人", None))
        self.label_5.setText(_translate("Form", "任务描述", None))
        self.label_6.setText(_translate("Form", "任务类型", None))
        self.label_2.setText(_translate("Form", "任务名称", None))
        self.label_4.setText(_translate("Form", "执行人", None))
        self.label_7.setText(_translate("Form", "优先级", None))
        self.label_9.setText(_translate("Form", "状 态", None))
        self.label_10.setText(_translate("Form", "TextLabel", None))
        self.cmb_TaskPriority.setItemText(0, _translate("Form", "请选择优先级", None))
        self.cmb_TaskPriority.setItemText(1, _translate("Form", "普通", None))
        self.cmb_TaskPriority.setItemText(2, _translate("Form", "中级", None))
        self.cmb_TaskPriority.setItemText(3, _translate("Form", "高级", None))
        self.label_12.setText(_translate("Form", "完成时间", None))
        self.cmb_TaskState.setItemText(0, _translate("Form", "请选择状态", None))
        self.cmb_TaskState.setItemText(1, _translate("Form", "未开始", None))
        self.cmb_TaskState.setItemText(2, _translate("Form", "已开始", None))
        self.cmb_TaskState.setItemText(3, _translate("Form", "已取消", None))
        self.cmb_TaskState.setItemText(4, _translate("Form", "已结束", None))
        self.lbl_createtime.setText(_translate("Form", "TextLabel", None))

import res_rc
