# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/task.ui'
#
# Created: Tue Dec 30 16:37:18 2014
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(644, 381)
        Form.setMaximumSize(QtCore.QSize(1000, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/mainicon/res/wp.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.pushButton_2 = QtGui.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 340, 80, 28))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayoutWidget = QtGui.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 634, 320))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.hzLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.hzLayout.setMargin(0)
        self.hzLayout.setObjectName(_fromUtf8("hzLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setVerticalSpacing(12)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.line = QtGui.QFrame(self.horizontalLayoutWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 5, 0, 1, 4)
        self.label_6 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1)
        self.dateTimeEdit_2 = QtGui.QDateTimeEdit(self.horizontalLayoutWidget)
        self.dateTimeEdit_2.setObjectName(_fromUtf8("dateTimeEdit_2"))
        self.gridLayout.addWidget(self.dateTimeEdit_2, 8, 3, 1, 1)
        self.txt_TaskNo = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.txt_TaskNo.setMinimumSize(QtCore.QSize(150, 0))
        self.txt_TaskNo.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txt_TaskNo.setObjectName(_fromUtf8("txt_TaskNo"))
        self.gridLayout.addWidget(self.txt_TaskNo, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.cmb_TaskPriority = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.cmb_TaskPriority.setObjectName(_fromUtf8("cmb_TaskPriority"))
        self.cmb_TaskPriority.addItem(_fromUtf8(""))
        self.cmb_TaskPriority.addItem(_fromUtf8(""))
        self.cmb_TaskPriority.addItem(_fromUtf8(""))
        self.cmb_TaskPriority.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmb_TaskPriority, 3, 1, 1, 1)
        self.txt_Creator = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.txt_Creator.setObjectName(_fromUtf8("txt_Creator"))
        self.gridLayout.addWidget(self.txt_Creator, 4, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.cmb_TaskState = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.cmb_TaskState.setObjectName(_fromUtf8("cmb_TaskState"))
        self.cmb_TaskState.addItem(_fromUtf8(""))
        self.cmb_TaskState.addItem(_fromUtf8(""))
        self.cmb_TaskState.addItem(_fromUtf8(""))
        self.cmb_TaskState.addItem(_fromUtf8(""))
        self.cmb_TaskState.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmb_TaskState, 3, 3, 1, 1)
        self.txt_TaskDescription = QtGui.QTextEdit(self.horizontalLayoutWidget)
        self.txt_TaskDescription.setObjectName(_fromUtf8("txt_TaskDescription"))
        self.gridLayout.addWidget(self.txt_TaskDescription, 10, 1, 1, 3)
        self.label_9 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 3, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 2, 1, 1)
        self.dateTimeEdit_4 = QtGui.QDateTimeEdit(self.horizontalLayoutWidget)
        self.dateTimeEdit_4.setObjectName(_fromUtf8("dateTimeEdit_4"))
        self.gridLayout.addWidget(self.dateTimeEdit_4, 8, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 8, 0, 1, 1)
        self.cmb_TaskType = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.cmb_TaskType.setMinimumSize(QtCore.QSize(150, 0))
        self.cmb_TaskType.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cmb_TaskType.setObjectName(_fromUtf8("cmb_TaskType"))
        self.cmb_TaskType.addItem(_fromUtf8(""))
        self.cmb_TaskType.addItem(_fromUtf8(""))
        self.cmb_TaskType.addItem(_fromUtf8(""))
        self.cmb_TaskType.addItem(_fromUtf8(""))
        self.cmb_TaskType.addItem(_fromUtf8(""))
        self.cmb_TaskType.addItem(_fromUtf8(""))
        self.cmb_TaskType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmb_TaskType, 1, 3, 1, 1)
        self.dateTimeEdit = QtGui.QDateTimeEdit(self.horizontalLayoutWidget)
        self.dateTimeEdit.setObjectName(_fromUtf8("dateTimeEdit"))
        self.gridLayout.addWidget(self.dateTimeEdit, 6, 3, 1, 1)
        self.txt_Requester = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.txt_Requester.setObjectName(_fromUtf8("txt_Requester"))
        self.gridLayout.addWidget(self.txt_Requester, 4, 3, 1, 1)
        self.line_2 = QtGui.QFrame(self.horizontalLayoutWidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 9, 0, 1, 4)
        self.label_12 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 6, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 8, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 10, 0, 1, 1)
        self.txt_TaskName = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.txt_TaskName.setObjectName(_fromUtf8("txt_TaskName"))
        self.gridLayout.addWidget(self.txt_TaskName, 0, 1, 1, 3)
        self.label_13 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 1, 0, 1, 1)
        self.hzLayout.addLayout(self.gridLayout)
        self.widget_task = QtGui.QWidget(self.horizontalLayoutWidget)
        self.widget_task.setObjectName(_fromUtf8("widget_task"))
        self.hzLayout.addWidget(self.widget_task)
        self.pushButton = QtGui.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(240, 340, 80, 28))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "任务", None))
        self.pushButton_2.setText(_translate("Form", "取消", None))
        self.label_6.setText(_translate("Form", "任务类型", None))
        self.label_3.setText(_translate("Form", "创建人", None))
        self.cmb_TaskPriority.setItemText(0, _translate("Form", "请选择优先级", None))
        self.cmb_TaskPriority.setItemText(1, _translate("Form", "普通", None))
        self.cmb_TaskPriority.setItemText(2, _translate("Form", "中级", None))
        self.cmb_TaskPriority.setItemText(3, _translate("Form", "高级", None))
        self.label_7.setText(_translate("Form", "优先级", None))
        self.cmb_TaskState.setItemText(0, _translate("Form", "请选择状态", None))
        self.cmb_TaskState.setItemText(1, _translate("Form", "未开始", None))
        self.cmb_TaskState.setItemText(2, _translate("Form", "已开始", None))
        self.cmb_TaskState.setItemText(3, _translate("Form", "已取消", None))
        self.cmb_TaskState.setItemText(4, _translate("Form", "已结束", None))
        self.label_9.setText(_translate("Form", "状态", None))
        self.label_2.setText(_translate("Form", "任务名称", None))
        self.label_4.setText(_translate("Form", "执行人", None))
        self.label_10.setText(_translate("Form", "期望执行时间", None))
        self.cmb_TaskType.setItemText(0, _translate("Form", "请选择任务类型", None))
        self.cmb_TaskType.setItemText(1, _translate("Form", "自动化", None))
        self.cmb_TaskType.setItemText(2, _translate("Form", "车机测试", None))
        self.cmb_TaskType.setItemText(3, _translate("Form", "App", None))
        self.cmb_TaskType.setItemText(4, _translate("Form", "Web平台", None))
        self.cmb_TaskType.setItemText(5, _translate("Form", "接口", None))
        self.cmb_TaskType.setItemText(6, _translate("Form", "性能测试", None))
        self.label_12.setText(_translate("Form", "结束时间", None))
        self.label_11.setText(_translate("Form", "实际执行时间", None))
        self.label_8.setText(_translate("Form", "创建时间", None))
        self.label_5.setText(_translate("Form", "任务描述", None))
        self.label_13.setText(_translate("Form", "任务编号", None))
        self.pushButton.setText(_translate("Form", "确定", None))

import res_rc
