# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/import_case.ui'
#
# Created: Wed Jan 28 17:33:35 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(850, 550)
        Dialog.setMinimumSize(QtCore.QSize(850, 550))
        Dialog.setMaximumSize(QtCore.QSize(850, 550))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/mainicon/res/wp.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.cmb_project = QtGui.QComboBox(Dialog)
        self.cmb_project.setMinimumSize(QtCore.QSize(180, 0))
        self.cmb_project.setObjectName(_fromUtf8("cmb_project"))
        self.cmb_project.addItem(_fromUtf8(""))
        self.cmb_project.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.cmb_project)
        self.cmb_nodes = QtGui.QComboBox(Dialog)
        self.cmb_nodes.setMinimumSize(QtCore.QSize(200, 0))
        self.cmb_nodes.setObjectName(_fromUtf8("cmb_nodes"))
        self.cmb_nodes.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.cmb_nodes)
        self.btn_excel = QtGui.QPushButton(Dialog)
        self.btn_excel.setMinimumSize(QtCore.QSize(110, 0))
        self.btn_excel.setObjectName(_fromUtf8("btn_excel"))
        self.horizontalLayout_2.addWidget(self.btn_excel)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_2 = QtGui.QPushButton(Dialog)
        self.pushButton_2.setMinimumSize(QtCore.QSize(170, 0))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_2.addWidget(self.line)
        self.excelLayout = QtGui.QHBoxLayout()
        self.excelLayout.setObjectName(_fromUtf8("excelLayout"))
        self.tree = QtGui.QTreeView(Dialog)
        self.tree.setMaximumSize(QtCore.QSize(240, 16777215))
        self.tree.setObjectName(_fromUtf8("tree"))
        self.excelLayout.addWidget(self.tree)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setContentsMargins(15, -1, 15, -1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineEdit = QtGui.QLineEdit(Dialog)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(180, 30))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout.addWidget(self.label_9)
        self.lineEdit_4 = QtGui.QLineEdit(Dialog)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.horizontalLayout.addWidget(self.lineEdit_4)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_2 = QtGui.QLineEdit(Dialog)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_3 = QtGui.QLineEdit(Dialog)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_3)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.label_7)
        self.textEdit = QtGui.QTextEdit(Dialog)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout.addWidget(self.textEdit)
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout.addWidget(self.label_8)
        self.textEdit_2 = QtGui.QTextEdit(Dialog)
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.verticalLayout.addWidget(self.textEdit_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lbl_tips = QtGui.QLabel(Dialog)
        self.lbl_tips.setStyleSheet(_fromUtf8("color: rgb(120,120,120);"))
        self.lbl_tips.setObjectName(_fromUtf8("lbl_tips"))
        self.horizontalLayout_3.addWidget(self.lbl_tips)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton = QtGui.QPushButton(Dialog)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.btn_modify = QtGui.QPushButton(Dialog)
        self.btn_modify.setObjectName(_fromUtf8("btn_modify"))
        self.horizontalLayout_3.addWidget(self.btn_modify)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.excelLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.excelLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "导入Excel", None))
        self.cmb_project.setItemText(0, _translate("Dialog", "选择项目", None))
        self.cmb_project.setItemText(1, _translate("Dialog", "新建项目", None))
        self.cmb_nodes.setItemText(0, _translate("Dialog", "选择父级分类", None))
        self.btn_excel.setText(_translate("Dialog", "选择Excel文件", None))
        self.pushButton_2.setText(_translate("Dialog", "确认无误，上传到服务器", None))
        self.label_4.setText(_translate("Dialog", "用例编号", None))
        self.label_9.setText(_translate("Dialog", "脚本", None))
        self.label_5.setText(_translate("Dialog", "分类", None))
        self.label_6.setText(_translate("Dialog", "用例名", None))
        self.label_7.setText(_translate("Dialog", "用例描述", None))
        self.label_8.setText(_translate("Dialog", "期望结果", None))
        self.lbl_tips.setText(_translate("Dialog", "可以在客户端对每个用例进行修改，也可以在Excel修改后重新导入", None))
        self.pushButton.setText(_translate("Dialog", "重置", None))
        self.btn_modify.setText(_translate("Dialog", "修改", None))

import res_rc
